### ISSUE TITLE
tls errors

### ISSUE THREAD

**Issue by NoSubstitute** [jimrollenhagen/pywhatauto#20]
Unhandled exception in thread started by <function download at 0x7fdc407f45f0>
Traceback (most recent call last):
  File "pywhatauto/WHATauto.py", line 595, in download
    retreived = dlCookie(downloadID, site, cj, target, network, name)
  File "pywhatauto/WHATauto.py", line 535, in dlCookie
    handle = getFile(downloadURL,cj)
  File "pywhatauto/WHATauto.py", line 750, in getFile
    return urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>

What can I update on my system to make it work again?

**Comment by philipbjorge** [comment]
Upgrading from python 2.7.8 to 2.7.10 resolved this error for me.
