### ISSUE TITLE
Unable to login to sites

### ISSUE THREAD

**Issue by harroguk** [jimrollenhagen/pywhatauto#21]
Executing the below command via IRC

`%download passthepopcorn 385761`
Downloading 385761 from passthepopcorn.    [pyWHATauto]

Produces the error...
Logging into passthepopcorn because a cookie was not previously saved or is outdated.
Unhandled exception in thread started by <function download at 0x027CEDF0>
Traceback (most recent call last):
  File "C:\InstalledPrograms\PyWhatAuto\WHATauto.py", line 595, in download
    retreived = dlCookie(downloadID, site, cj, target, network, name)
  File "C:\InstalledPrograms\PyWhatAuto\WHATauto.py", line 495, in dlCookie
    cj = createCookie(site, cj)
  File "C:\InstalledPrograms\PyWhatAuto\WHATauto.py", line 797, in createCookie
    handle = urlopen(req)
  File "C:\InstalledPrograms\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\InstalledPrograms\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\InstalledPrograms\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\InstalledPrograms\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\InstalledPrograms\Python27\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\InstalledPrograms\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>

**Comment by harroguk** [comment]
Seems that updating from Python 2.7.4 to 2.7.10 resolved this issue
